"""new sys db

Revision ID: 5cb6f353c1c5
Revises: 
Create Date: 2020-02-24 22:57:09.025065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb6f353c1c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Candidate_Name'), 'Candidate', ['Name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Candidate_Name'), table_name='Candidate')
    # ### end Alembic commands ###
