"""new file column

Revision ID: 5d1ad3cde2fc
Revises: 8dac6cd030bc
Create Date: 2020-02-26 23:43:14.851437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1ad3cde2fc'
down_revision = '8dac6cd030bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Polling Station', sa.Column('file', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Polling Station', 'file')
    # ### end Alembic commands ###
