"""updates

Revision ID: 8dac6cd030bc
Revises: 5cb6f353c1c5
Create Date: 2020-02-24 23:27:21.478611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dac6cd030bc'
down_revision = '5cb6f353c1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Candidate_Name', table_name='Candidate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Candidate_Name', 'Candidate', ['Name'], unique=1)
    # ### end Alembic commands ###
